## Link al notebook con las celdas de python para la resolucion de los ejercicios
https://github.com/JesuaVAlc/Deberes-Metodos-Numericos/blob/main/Tarea11_JesuaVillacis.ipynb

**1.** Encuentre las primeras dos iteraciones del método de Jacobi para los siguientes sistemas lineales, por
medio de $𝐱^{(𝟎)} = 0$:


In [2]:
import numpy as np

In [53]:
def gauss_jacobi(A, b, tol, max_iter, x0=None):
    n = len(b)
    x = np.zeros(n) if x0 is None else x0.copy()
    x_new = np.zeros(n)

    for k in range(max_iter):
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        
        if k < 50:
            print(f"Iteración {k+1}: {x_new}")
        elif k == 100:
            print("\n...Aún se están realizando iteraciones...\n")

        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new
        
        x[:] = x_new

    return x

def gauss_seidel(A, b, tol, max_iter, x0=None):
    n = len(b)
    x = np.zeros(n) if x0 is None else x0.copy()

    for k in range(max_iter):
        x_old = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x[j] for j in range(i))
            s2 = sum(A[i][j] * x_old[j] for j in range(i + 1, n))
            x[i] = (b[i] - s1 - s2) / A[i][i]

        if k < 50:
            print(f"Iteración {k+1}: {x}")
        elif k == 100:
            print("\n...Aún se están realizando iteraciones...\n")

        if np.linalg.norm(x - x_old, ord=np.inf) < tol:
            return x

    return x

**a)**
\begin{gather*}
3 x_{1} - x_{2} + x_{3} = 1, \\
3 x_{1} + 6 x_{2} + 2 x_{3} = 0, \\
3 x_{1} + 3 x_{2} + 7 x_{3} = 4.
\end{gather*}

In [31]:
A = np.array([[3, -1, 1],
              [3, 6, 2],
              [3, 3, 7]], dtype=float)

b = np.array([1, 0, 4], dtype=float)
print('Resultado:\n',gauss_jacobi(A, b, 1e-2, 2))

Iteración 1: [0.33333333 0.         0.57142857]
Iteración 2: [ 0.14285714 -0.35714286  0.42857143]
Resultado:
 [ 0.14285714 -0.35714286  0.42857143]


**b)**
\begin{gather*}
10 x_{1} - x_{2} = 9, \\
- x_{1} + 10 x_{2} - 2 x_{3} = 7, \\
-2x_2+10x_3=6
\end{gather*}

In [32]:
A = np.array([[10, -1, 0],
              [-1, 10, -2],
              [0, -2, 10]], dtype=float)
b = np.array([9, 7, 6], dtype=float)
print('Resultado:\n',gauss_jacobi(A, b, 1e-2, 2))

Iteración 1: [0.9 0.7 0.6]
Iteración 2: [0.97 0.91 0.74]
Resultado:
 [0.97 0.91 0.74]


**c)**
\begin{gather*}
10 x_{1} + 5 x_{2} = 6,\\
5 x_{1} + 10 x_{2} - 4 x_{3} = 25, \\
-4 x_{2} + 8 x_{3} - x_{4} = -11, \\
- x_{3} + 5 x_{4} = -11, \\
\end{gather*}

In [33]:
A = np.array([[10, 5, 0, 0],
              [5, 10, -4, 0],
              [0, -4, 8, -1],
              [0, 0, -1, 5]], dtype=float)
b = np.array([6, 25, -11, -11], dtype=float)
print('Resultado:\n',gauss_jacobi(A, b, 1e-2, 2))

Iteración 1: [ 0.6    2.5   -1.375 -2.2  ]
Iteración 2: [-0.65   1.65  -0.4   -2.475]
Resultado:
 [-0.65   1.65  -0.4   -2.475]


**d)**
\begin{gather*}
4 x_{1} + x_{2} + x_{3} + x_{5} = 6, \\
- x_{1} - 3 x_{2} + x_{3} + x_{4} = 6, \\
2 x_{1} + x_{2} + 5 x_{3} - x_{4} - x_{5} = 6, \\
- x_{1} - x_{2} - x_{3} + 4 x_{4} = 6,
\end{gather*}

In [34]:
A = np.array([[4, 1, 1, 0, 1],
              [-1, -3, 1, 1, 0],
              [2, 1, 5, -1, -1],
              [-1, -1, -1, 4, 0],
              [0, 2, -1, 1, 4]], dtype=float)
b = np.array([6, 6, 6, 6, 6], dtype=float)
print('Resultado:\n',gauss_jacobi(A, b, 1e-2, 2))

Iteración 1: [ 1.5 -2.   1.2  1.5  1.5]
Iteración 2: [ 1.325 -1.6    1.6    1.675  2.425]
Resultado:
 [ 1.325 -1.6    1.6    1.675  2.425]


**2.** Repita el ejercicio 1 usando el método de Gauss-Siedel.

**a)**

In [38]:
A = np.array([[3, -1, 1],
              [3, 6, 2],
              [3, 3, 7]], dtype=float)

b = np.array([1, 0, 4], dtype=float)
print('Resultado en dos iteraciones:\n',gauss_seidel(A, b, 1e-2, 2))

Iteración 1: [ 0.33333333 -0.16666667  0.5       ]
Iteración 2: [ 0.11111111 -0.22222222  0.61904762]
Resultado en dos iteraciones:
 [ 0.11111111 -0.22222222  0.61904762]


**b)**

In [37]:
A = np.array([[10, -1, 0],
              [-1, 10, -2],
              [0, -2, 10]], dtype=float)
b = np.array([9, 7, 6], dtype=float)
print('Resultado en dos iteraciones:\n',gauss_seidel(A, b, 1e-2, 2))

Iteración 1: [0.9   0.79  0.758]
Iteración 2: [0.979  0.9495 0.7899]
Resultado en dos iteraciones:
 [0.979  0.9495 0.7899]


**c)**

In [36]:
A = np.array([[10, 5, 0, 0],
              [5, 10, -4, 0],
              [0, -4, 8, -1],
              [0, 0, -1, 5]], dtype=float)
b = np.array([6, 25, -11, -11], dtype=float)
print('Resultado en dos iteraciones:\n',gauss_seidel(A, b, 1e-2, 2))

Iteración 1: [ 0.6    2.2   -0.275 -2.255]
Iteración 2: [-0.5       2.64     -0.336875 -2.267375]
Resultado en dos iteraciones:
 [-0.5       2.64     -0.336875 -2.267375]


**d)**

In [35]:
A = np.array([[4, 1, 1, 0, 1],
              [-1, -3, 1, 1, 0],
              [2, 1, 5, -1, -1],
              [-1, -1, -1, 4, 0],
              [0, 2, -1, 1, 4]], dtype=float)
b = np.array([6, 6, 6, 6, 6], dtype=float)
print('Resultado en dos iteraciones:\n',gauss_seidel(A, b, 1e-2, 2))

Iteración 1: [ 1.5     -2.5      1.1      1.525    2.64375]
Iteración 2: [ 1.1890625  -1.52135417  1.86239583  1.88252604  2.25564453]
Resultado en dos iteraciones:
 [ 1.1890625  -1.52135417  1.86239583  1.88252604  2.25564453]


**3.** Utilice el método de Jacobi para resolver los sistemas lineales en el ejercicio 1, con TOL = 10-3.

**a)**

In [21]:
A = np.array([[3, -1, 1],
              [3, 6, 2],
              [3, 3, 7]], dtype=float)

b = np.array([1, 0, 4], dtype=float)
print('Resultado:\n',gauss_jacobi(A, b, 1e-2, 100))

Iteración 1: [0.33333333 0.         0.57142857]
Iteración 2: [ 0.14285714 -0.35714286  0.42857143]
Iteración 3: [ 0.07142857 -0.21428571  0.66326531]
Iteración 4: [ 0.04081633 -0.25680272  0.63265306]
Iteración 5: [ 0.03684807 -0.23129252  0.66399417]
Iteración 6: [ 0.03490444 -0.23975543  0.6547619 ]
Resultado:
 [ 0.03490444 -0.23975543  0.6547619 ]


**b)**

In [22]:
A = np.array([[10, -1, 0],
              [-1, 10, -2],
              [0, -2, 10]], dtype=float)
b = np.array([9, 7, 6], dtype=float)
print('Resultado:\n',gauss_jacobi(A, b, 1e-2, 100))

Iteración 1: [0.9 0.7 0.6]
Iteración 2: [0.97 0.91 0.74]
Iteración 3: [0.991 0.945 0.782]
Iteración 4: [0.9945 0.9555 0.789 ]
Iteración 5: [0.99555 0.95725 0.7911 ]
Resultado:
 [0.99555 0.95725 0.7911 ]


**c)**

In [23]:
A = np.array([[10, 5, 0, 0],
              [5, 10, -4, 0],
              [0, -4, 8, -1],
              [0, 0, -1, 5]], dtype=float)
b = np.array([6, 25, -11, -11], dtype=float)
print('Resultado:\n',gauss_jacobi(A, b, 1e-2, 100))

Iteración 1: [ 0.6    2.5   -1.375 -2.2  ]
Iteración 2: [-0.65   1.65  -0.4   -2.475]
Iteración 3: [-0.225     2.665    -0.859375 -2.28    ]
Iteración 4: [-0.7325    2.26875  -0.3275   -2.371875]
Iteración 5: [-0.534375    2.73525    -0.53710938 -2.2655    ]
Iteración 6: [-0.767625    2.55234375 -0.2905625  -2.30742188]
Iteración 7: [-0.67617187  2.7675875  -0.38725586 -2.2581125 ]
Iteración 8: [-0.78379375  2.68318359 -0.27347031 -2.27745117]
Iteración 9: [-0.7415918   2.78250875 -0.3180896  -2.25469406]
Iteración 10: [-0.79125437  2.74356006 -0.26558238 -2.26361792]
Iteración 11: [-0.77178003  2.78939423 -0.28617221 -2.25311648]
Iteración 12: [-0.79469712  2.77142113 -0.26194244 -2.25723444]
Iteración 13: [-0.78571057  2.79257158 -0.27144374 -2.25238849]
Iteración 14: [-0.79628579  2.78427779 -0.26026277 -2.25428875]
Iteración 15: [-0.79213889  2.79403779 -0.2646472  -2.25205255]
Resultado:
 [-0.79213889  2.79403779 -0.2646472  -2.25205255]


**d)**

In [24]:
A = np.array([[4, 1, 1, 0, 1],
              [-1, -3, 1, 1, 0],
              [2, 1, 5, -1, -1],
              [-1, -1, -1, 4, 0],
              [0, 2, -1, 1, 4]], dtype=float)
b = np.array([6, 6, 6, 6, 6], dtype=float)
print('Resultado:\n',gauss_jacobi(A, b, 1e-2, 100))

Iteración 1: [ 1.5 -2.   1.2  1.5  1.5]
Iteración 2: [ 1.325 -1.6    1.6    1.675  2.425]
Iteración 3: [ 0.89375 -1.35     1.81     1.83125  2.28125]
Iteración 4: [ 0.8146875  -1.08416667  1.935       1.8384375   2.1696875 ]
Iteración 5: [ 0.74486979 -1.01375     1.89258333  1.91638021  2.06622396]
Iteración 6: [ 0.76373568 -0.97863542  1.90132292  1.90592578  2.00092578]
Iteración 7: [ 0.76909668 -0.98549566  1.87160313  1.92160579  1.98816699]
Iteración 8: [ 0.78143139 -0.99196259  1.87141502  1.91380104  1.98024716]
Iteración 9: [ 0.7850751  -0.99873844  1.8646296   1.91522095  1.98538479]
Resultado:
 [ 0.7850751  -0.99873844  1.8646296   1.91522095  1.98538479]


**4.** Utilice el método de Gauss-Siedel para resolver los sistemas lineales en el ejercicio 1, con TOL = 10-3.

**a)**

In [25]:
A = np.array([[3, -1, 1],
              [3, 6, 2],
              [3, 3, 7]], dtype=float)

b = np.array([1, 0, 4], dtype=float)
print('Resultado:\n',gauss_seidel(A, b, 1e-2, 100))

Iteración 1: [ 0.33333333 -0.16666667  0.5       ]
Iteración 2: [ 0.11111111 -0.22222222  0.61904762]
Iteración 3: [ 0.05291005 -0.23280423  0.64852608]
Iteración 4: [ 0.03955656 -0.23595364  0.65559875]
Iteración 5: [ 0.0361492  -0.23660752  0.65733928]
Resultado:
 [ 0.0361492  -0.23660752  0.65733928]


**b)**

In [26]:
A = np.array([[10, -1, 0],
              [-1, 10, -2],
              [0, -2, 10]], dtype=float)
b = np.array([9, 7, 6], dtype=float)
print('Resultado:\n',gauss_seidel(A, b, 1e-2, 100))

Iteración 1: [0.9   0.79  0.758]
Iteración 2: [0.979  0.9495 0.7899]
Iteración 3: [0.99495  0.957475 0.791495]
Iteración 4: [0.9957475  0.95787375 0.79157475]
Resultado:
 [0.9957475  0.95787375 0.79157475]


**c)**

In [27]:
A = np.array([[10, 5, 0, 0],
              [5, 10, -4, 0],
              [0, -4, 8, -1],
              [0, 0, -1, 5]], dtype=float)
b = np.array([6, 25, -11, -11], dtype=float)
print('Resultado:\n',gauss_seidel(A, b, 1e-2, 100))

Iteración 1: [ 0.6    2.2   -0.275 -2.255]
Iteración 2: [-0.5       2.64     -0.336875 -2.267375]
Iteración 3: [-0.72        2.72525    -0.29579688 -2.25915938]
Iteración 4: [-0.762625    2.76299375 -0.27589805 -2.25517961]
Iteración 5: [-0.78149687  2.78038922 -0.26670284 -2.25334057]
Iteración 6: [-0.79019461  2.78841617 -0.26245949 -2.2524919 ]
Resultado:
 [-0.79019461  2.78841617 -0.26245949 -2.2524919 ]


**d)**

In [28]:
A = np.array([[4, 1, 1, 0, 1],
              [-1, -3, 1, 1, 0],
              [2, 1, 5, -1, -1],
              [-1, -1, -1, 4, 0],
              [0, 2, -1, 1, 4]], dtype=float)
b = np.array([6, 6, 6, 6, 6], dtype=float)
print('Resultado:\n',gauss_seidel(A, b, 1e-2, 100))

Iteración 1: [ 1.5     -2.5      1.1      1.525    2.64375]
Iteración 2: [ 1.1890625  -1.52135417  1.86239583  1.88252604  2.25564453]
Iteración 3: [ 0.85082845 -1.03530219  1.89436317  1.92747236  2.0093738 ]
Iteración 4: [ 0.7828913  -0.98701859  1.87161643  1.91687229  1.98219533]
Iteración 5: [ 0.78330171 -0.998271    1.86614704  1.91279444  1.98747365]
Iteración 6: [ 0.78616258 -1.00240703  1.86606999  1.91245638  1.98960692]
Resultado:
 [ 0.78616258 -1.00240703  1.86606999  1.91245638  1.98960692]


**5.** El sistema lineal
\begin{align*}
2 x_{1} - x_{2} + x_{3} &= -1, \\
2 x_{1} + 2 x_{2} + 2 x_{3} &= 4, \\
- x_{1} - x_{2} + 2 x_{3} &= -5,
\end{align*}

tiene la solución (1, 2, -1)

**a)** Muestre que el método de Jacobi con x(0) = 0 falla al proporcionar una buena aproximación
después de 25 iteraciones.


In [29]:
A = np.array([[2, -1, 1],
              [2, 2, 2],
              [-1, -1, 2]])
b = np.array([-1, 4, -5])
print('Resultado en 25 iteraciones:\n',gauss_jacobi(A, b, 1e-2, 25))


Iteración 1: [-0.5  2.  -2.5]
Iteración 2: [ 1.75  5.   -1.75]
Iteración 3: [2.875 2.    0.875]
Iteración 4: [ 0.0625 -1.75   -0.0625]
Iteración 5: [-1.34375  2.      -3.34375]
Iteración 6: [ 2.171875  6.6875   -2.171875]
Iteración 7: [3.9296875 2.        1.9296875]
Iteración 8: [-0.46484375 -3.859375    0.46484375]
Iteración 9: [-2.66210938  2.         -4.66210938]
Iteración 10: [ 2.83105469  9.32421875 -2.83105469]
Iteración 11: [5.57763672 2.         3.57763672]
Iteración 12: [-1.28881836 -7.15527344  1.28881836]
Iteración 13: [-4.7220459  2.        -6.7220459]
Iteración 14: [ 3.86102295 13.4440918  -3.86102295]
Iteración 15: [8.15255737 2.         6.15255737]
Iteración 16: [ -2.57627869 -12.30511475   2.57627869]
Iteración 17: [-7.94069672  2.         -9.94069672]
Iteración 18: [ 5.47034836 19.88139343 -5.47034836]
Iteración 19: [12.1758709  2.        10.1758709]
Iteración 20: [ -4.58793545 -20.35174179   4.58793545]
Iteración 21: [-12.96983862   2.         -14.96983862]
Iteración 

**b)** Utilice el método de Gauss-Siedel con x(0) = 0:para aproximar la solución para el sistema lineal
dentro de $10^{−5}$.


In [30]:
A = np.array([[2, -1, 1],
              [2, 2, 2],
              [-1, -1, 2]])
b = np.array([-1, 4, -5])
print('Resultado con una tolerancia de 10e-5:\n',gauss_seidel(A, b, 1e-5, 100))

Iteración 1: [-0.5  2.5 -1.5]
Iteración 2: [ 1.5   2.   -0.75]
Iteración 3: [ 0.875  1.875 -1.125]
Iteración 4: [ 1.      2.125  -0.9375]
Iteración 5: [ 1.03125  1.90625 -1.03125]
Iteración 6: [ 0.96875   2.0625   -0.984375]
Iteración 7: [ 1.0234375  1.9609375 -1.0078125]
Iteración 8: [ 0.984375    2.0234375  -0.99609375]
Iteración 9: [ 1.00976562  1.98632812 -1.00195312]
Iteración 10: [ 0.99414062  2.0078125  -0.99902344]
Iteración 11: [ 1.00341797  1.99560547 -1.00048828]
Iteración 12: [ 0.99804688  2.00244141 -0.99975586]
Iteración 13: [ 1.00109863  1.99865723 -1.00012207]
Iteración 14: [ 0.99938965  2.00073242 -0.99993896]
Iteración 15: [ 1.00033569  1.99960327 -1.00003052]
Iteración 16: [ 0.99981689  2.00021362 -0.99998474]
Iteración 17: [ 1.00009918  1.99988556 -1.00000763]
Iteración 18: [ 0.99994659  2.00006104 -0.99999619]
Iteración 19: [ 1.00002861  1.99996758 -1.00000191]
Iteración 20: [ 0.99998474  2.00001717 -0.99999905]
Iteración 21: [ 1.00000811  1.99999094 -1.00000048]
I

**6.** El sistema lineal
\begin{gather*}
x_{1} \quad - x_{3} = 0.2, \\
-\frac{1}{2} x_{1} + x_{2} - \frac{1}{4} x_{3} = -1.425, \\
x_{1} - \frac{1}{2} x_{2} + x_{3} = 2,
\end{gather*}
tiene la solución (0.9, -0.8, 0.7)




**a.)** ¿La matriz de coeficientes 
\begin{align*}
A = \begin{bmatrix}
1 & 0 & -1 \\
-\frac{1}{2} & 1 & -\frac{1}{4} \\
1 & -\frac{1}{2} & 1
\end{bmatrix}
\end{align*}
tiene diagonal estrictamente dominante?

*R=* Si, tiene una diagonal estrictamente dominante, porque todos sus valores de la diagonal son mayores a la suma de los demas elementos de cada fila.


**b)** Utilice el método iterativo de Gauss-Siedel para aproximar la solución para el sistema lineal con
una tolerancia de 1e-22 y un máximo de 300 iteraciones.

In [54]:
A = np.array([
    [1,   0,    -1],
    [0.5,   1,    -0.25],  
    [1,  -0.5,     1]
], dtype=float)

b = np.array([0.2, -1.425, 2], dtype=float)
x = gauss_seidel(A,b, 10e-22, 300)
print('Resultado en 300 iteraciones:' , x)

Iteración 1: [ 0.2    -1.525   1.0375]
Iteración 2: [ 1.2375    -1.784375  -0.1296875]
Iteración 3: [ 0.0703125  -1.49257813  1.18339844]
Iteración 4: [ 1.38339844 -1.82084961 -0.29382324]
Iteración 5: [-0.09382324 -1.45154419  1.36805115]
Iteración 6: [ 1.56805115 -1.86701279 -0.50155754]
Iteración 7: [-0.30155754 -1.39961061  1.60175223]
Iteración 8: [ 1.80175223 -1.92543806 -0.76447126]
Iteración 9: [-0.56447126 -1.33388218  1.89753017]
Iteración 10: [ 2.09753017 -1.99938254 -1.09722144]
Iteración 11: [-0.89722144 -1.25069464  2.27187412]
Iteración 12: [ 2.47187412 -2.09296853 -1.51835839]
Iteración 13: [-1.31835839 -1.1454104   2.74565319]
Iteración 14: [ 2.94565319 -2.2114133  -2.05135983]
Iteración 15: [-1.85135983 -1.01216004  3.34527981]
Iteración 16: [ 3.54527981 -2.36131995 -2.72593979]
Iteración 17: [-2.52593979 -0.84351505  4.10418226]
Iteración 18: [ 4.30418226 -2.55104557 -3.57970505]
Iteración 19: [-3.37970505 -0.63007374  5.06466818]
Iteración 20: [ 5.26466818 -2.791167

**c)** ¿Qué pasa en la parte b) cuando el sistema cambia por el siguiente?
\begin{gather*}
x_{1} - 2 x_{3} = 0.2, \\
-\frac{1}{2} x_{1} + x_{2} - \frac{1}{4} x_{3} = -1.425, \\
x_{1} - \frac{1}{2} x_{2} + x_{3} = 2.
\end{gather*}

In [56]:
A = np.array([
    [1,   0,    -2],
    [0.5,   1,    -0.25],  
    [1,  -0.5,     1]
], dtype=float)

b = np.array([0.2, -1.425, 2], dtype=float)
x = gauss_seidel(A,b, 10e-22, 300)
print('Resultado en 300 iteraciones: ', x)

Iteración 1: [ 0.2    -1.525   1.0375]
Iteración 2: [ 2.275     -2.303125  -1.4265625]
Iteración 3: [-2.653125   -0.45507812  4.42558594]
Iteración 4: [ 9.05117187 -4.84418945 -9.4732666 ]
Iteración 5: [-18.7465332    5.57994995  23.53650818]
Iteración 6: [ 47.27301636 -19.17738113 -54.86170692]
Iteración 7: [-109.52341385   39.62128019  131.33405395]
Iteración 8: [ 262.86810789 -100.02554046 -310.88087812]
Iteración 9: [-621.56175624  231.63565859  739.37958554]
Iteración 10: [ 1478.95917107  -556.05968915 -1754.98901565]
Iteración 11: [-3509.7780313   1314.71676174  4169.13641217]
Iteración 12: [ 8338.47282433 -3128.37730913 -9900.6614789 ]
Iteración 13: [-19801.12295779   7423.97110917  23515.10851238]
Iteración 14: [ 47030.41702476 -17637.85638429 -55847.3452169 ]
Iteración 15: [-111694.49043381   41883.98391268  132638.48239015]
Iteración 16: [ 265277.16478029  -99480.38679261 -315015.3581766 ]
Iteración 17: [-630030.5163532   236259.99363245  748162.51316942]
Iteración 18: [ 1496

**7.** Repita el ejercicio 11 usando el método de Jacobi

In [57]:
A = np.array([
    [1,   0,    -1],
    [0.5,   1,    -0.25],  
    [1,  -0.5,     1]
], dtype=float)

b = np.array([0.2, -1.425, 2], dtype=float)
x = gauss_jacobi(A,b, 10e-22, 300)
print('Resultado en 300 iteraciones: ', x)

Iteración 1: [ 0.2   -1.425  2.   ]
Iteración 2: [ 2.2    -1.025   1.0875]
Iteración 3: [ 1.2875   -2.253125 -0.7125  ]
Iteración 4: [-0.5125    -2.246875  -0.4140625]
Iteración 5: [-0.2140625  -1.27226562  1.3890625 ]
Iteración 6: [ 1.5890625  -0.97070312  1.57792969]
Iteración 7: [ 1.77792969 -1.82504883 -0.07441406]
Iteración 8: [ 0.12558594 -2.33256836 -0.6904541 ]
Iteración 9: [-0.4904541  -1.66040649  0.70812988]
Iteración 10: [ 0.90812988 -1.00274048  1.66025085]
Iteración 11: [ 1.86025085 -1.46400223  0.59049988]
Iteración 12: [ 0.79049988 -2.20750046 -0.59225197]
Iteración 13: [-0.39225197 -1.96831293  0.10574989]
Iteración 14: [ 0.30574989 -1.20243654  1.4080955 ]
Iteración 15: [ 1.6080955  -1.22585107  1.09303184]
Iteración 16: [ 1.29303184 -1.95578979 -0.22102104]
Iteración 17: [-0.02102104 -2.12677118 -0.27092673]
Iteración 18: [-0.07092673 -1.48222116  0.95763545]
Iteración 19: [ 1.15763545 -1.15012777  1.32981615]
Iteración 20: [ 1.52981615 -1.67136369  0.26730066]
Itera

**8.** Un cable coaxial está formado por un conductor interno de 0.1 pulgadas cuadradas y un conductor externo
de 0.5 pulgadas cuadradas. El potencial en un punto en la sección transversal del cable se describe
mediante la ecuación de Laplace.
Suponga que el conductor interno se mantiene en 0 volts y el conductor externo se mantiene en 110 volts. Aproximar
el potencial entre los dos conductores requiere resolver el siguiente sistema lineal.

\begin{align*}
\left[
\begin{array}{rrrrrrrrrrrr}
4 & -1 & 0 & 0 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
-1 & 4 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & -1 & 4 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & -1 & 4 & 0 & -1 & 0 & 0 & 0 & 0 & 0 & 0 \\
-1 & 0 & 0 & 0 & 4 & 0 & -1 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & -1 & 0 & 4 & 0 & -1 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & -1 & 0 & 4 & 0 & -1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & -1 & 0 & 4 & 0 & 0 & 0 & -1 \\
0 & 0 & 0 & 0 & 0 & 0 & -1 & 0 & 4 & -1 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 4 & -1 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 4 & -1 \\
0 & 0 & 0 & 0 & 0 & -1 & 0 & 0 & 0 & 0 & -1 & 4
\end{array}
\right]
\left[
\begin{array}{l}
w_{1} \\
w_{2} \\
w_{3} \\
w_{4} \\
w_{5} \\
w_{6} \\
w_{7} \\
w_{8} \\
w_{9} \\
w_{10} \\
w_{11} \\
w_{12}
\end{array}
\right]
=
\left[
\begin{array}{l}
220 \\
110 \\
110 \\
220 \\
110 \\
110 \\
110 \\
110 \\
220 \\
110 \\
110 \\
220
\end{array}
\right]
\end{align*}

**a)** ¿La matriz es estrictamente diagonalmente dominante?

*R=* Si, ya que los valores de la diagonal son mayores siempre.


**b)** Resuelva el sistema lineal usando el método de Jacobi con x(0) = 0 y TOL = 10-2.

In [45]:
A = np.array([
    [ 4, -1,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0],
    [-1,  4, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
    [ 0, -1,  4, -1,  0,  0,  0,  0,  0,  0,  0,  0],
    [ 0,  0, -1,  4,  0, -1,  0,  0,  0,  0,  0,  0],
    [-1, 0,  0,  0,  4,  0, -1,  0,  0,  0,  0,  0],
    [ 0, 0,  0, -1,  0,  4,  0, -1,  0,  0,  0,  0],
    [ 0, 0,  0,  0, -1,  0,  4,  0, -1,  0,  0,  0],
    [ 0, 0,  0,  0,  0, -1,  0,  4,  0,  0,  0, -1],
    [ 0, 0,  0,  0,  0,  0, -1,  0,  4, -1,  0,  0],
    [ 0, 0,  0,  0,  0,  0,  0,  0, -1,  4, -1,  0],
    [ 0, 0,  0,  0,  0,  0,  0,  0,  0, -1,  4, -1],
    [ 0, 0,  0,  0,  0,  0,  0, -1,  0,  0, -1,  4]
], dtype=float)

b = np.array([
    220, 110, 110, 220,
    110, 110, 110, 110,
    220, 110, 110, 220
], dtype=float)
print('Resultado Gauss-Jacobi:\n', gauss_jacobi(A,b, 10e-2, 100))

Iteración 1: [55.  27.5 27.5 55.  27.5 27.5 27.5 27.5 55.  27.5 27.5 55. ]
Iteración 2: [68.75  48.125 48.125 68.75  48.125 48.125 48.125 48.125 68.75  48.125
 48.125 68.75 ]
Iteración 3: [79.0625  56.71875 56.71875 79.0625  56.71875 56.71875 56.71875 56.71875
 79.0625  56.71875 56.71875 79.0625 ]
Iteración 4: [83.359375  61.4453125 61.4453125 83.359375  61.4453125 61.4453125
 61.4453125 61.4453125 83.359375  61.4453125 61.4453125 83.359375 ]
Iteración 5: [85.72265625 63.70117188 63.70117188 85.72265625 63.70117188 63.70117188
 63.70117188 63.70117188 85.72265625 63.70117188 63.70117188 85.72265625]
Iteración 6: [86.85058594 64.85595703 64.85595703 86.85058594 64.85595703 64.85595703
 64.85595703 64.85595703 86.85058594 64.85595703 64.85595703 86.85058594]
Iteración 7: [87.42797852 65.42663574 65.42663574 87.42797852 65.42663574 65.42663574
 65.42663574 65.42663574 87.42797852 65.42663574 65.42663574 87.42797852]
Iteración 8: [87.71331787 65.71365356 65.71365356 87.71331787 65.71365356

**c)** Repita la parte b) mediante el método de Gauss-Siedel.

In [46]:
print('Resultado Gauss-Seidel:\n', gauss_seidel(A,b, 10e-2, 100))

Iteración 1: [55.         41.25       37.8125     64.453125   41.25       43.61328125
 37.8125     38.40332031 64.453125   43.61328125 38.40332031 74.20166016]
Iteración 2: [75.625      55.859375   57.578125   80.29785156 55.859375   57.17529297
 57.578125   60.34423828 80.29785156 57.17529297 60.34423828 85.17211914]
Iteración 3: [82.9296875  62.62695312 63.23120117 85.10162354 62.62695312 63.86146545
 63.23120117 64.75839615 85.10162354 63.86146545 64.75839615 87.37919807]
Iteración 4: [86.31347656 64.88616943 64.99694824 87.21460342 64.88616943 65.49324989
 64.99694824 65.71811199 87.21460342 65.49324989 65.71811199 87.859056  ]
Iteración 5: [87.44308472 65.61000824 65.70615292 87.7998507  65.61000824 65.87949067
 65.70615292 65.93463667 87.7998507  65.87949067 65.93463667 87.96731833]
Iteración 6: [87.80500412 65.87778926 65.91940999 87.94972517 65.87778926 65.97109046
 65.91940999 65.9846022  87.94972517 65.97109046 65.9846022  87.9923011 ]
Iteración 7: [87.93889463 65.96457615 65